export  const APP_HEADER="POKEMON APP";
export  const APP_SUB_HEADER="Pokemon V1"
export  const LOADING_TEXT="Yükleniyor Lütfen Bekleyiniz ...";
export  const  SERVER_ERROR_TEXT="Beklenmedik Bir Hata Gerçekleşti Lütfen Daha Sonra Tekrar Deneyin"
export  const  POKE_DETAIL_ERROR="POKEMON BULUNAMADI"
export  const POKE_DETAIL_IMAGES="Resimler"
export  const POKE_DETAIL_SUMMARY="Detaylar"
export  const  POKE_DETAIL_ABILITIES="Yetenekleri"
export  const  POKE_DETAIL_TYPES="Türleri"
export  const POKE_DETAIL_HEIGHT="Yükseklik";
export  const  POKE_DETAIL_WEIGHT="Ağırlık";
export  const  POKE_DETAIL_STATS="İstatistikler";
export  const BACK_HOME="Anasayfaya Dön";
export  const ADD_CATCH_POKE="ADD_CATCH_POKE"
export  const REMOVE_CATCH_POKE="REMOVE_CATCH_POKE"
export  const TOTAL_CATCHED_POKE_COUNT="Yakalanan Toplam Pokemon Sayısı :"
export  const SWITCH_DARK="Koyu Temaya Geç"
export  const SWITCH_LIGHT="Açık Temaya Geç"
export  const ALREADY_CATCHED="Bu Pokemon Zaten Yakalandı"
export  const SUCCESS_CATCH="Pokemon Yakalandı"
export  const CATH_POKE="Pokemonunu Yakala";
export const POKE_DETAIL="Pokemon Detayları.."
export  const SHOW_CATCHED_POKE_LIST="Yakalanan Pokemonları Göster";
export const NO_CATCHED_POKEMONS="Henüz Hiç Pokemon Yakalamadınız Buraya Tıklayarak Yakalamaya Başlayın"
export const NO_CATCHED_POKEMONS_FOOTER="Henüz Hiç Pokemon Yakalamadınız Hadi Hemen Yakala"
export  const CATCHED_POKE_LIST_TITLE="Yakalanan Pokemonlar Listeniz"
export const RELEASE_CATCHED_POKE="Pokemonu Serbest Bırak"
export const SUCCESS_RELEASE="Pokemon Serbest Bırakıldı"
export const FAVORITE_POCKES="Favori Pokemonlarım"
export const REMOVE_FAVORITE="Favorilerimden Çıkar"